title: Mini Data Engine Lab
description: Interactive Data Systems Lab with runnable PostgreSQL-like and Databricks-like internals in Python and Rust.
theme: minima
markdown: kramdown

url: "https://kroq86.github.io"
baseurl: "/data-engineering-runtime-lab"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

seo:
  type: WebSite
  name: Mini Data Engine Lab
  links:
    - https://github.com/kroq86/data-engineering-runtime-lab
